#!/usr/bin/env python3
"""Generate config/arm_physical.yaml from the CAD export and the actuator list.

The SolidWorks exporter only knows the mass of the printed/machined parts.
A real arm also carries its actuators, so every link here gets the servo that
sits in it lumped in (parallel-axis theorem). Collision primitives are derived
from the mesh bounding boxes, which is what industrial robot packages usually
ship: cheap boxes for collision checking, detailed meshes for visuals.

Run from the package root after changing the CAD or the actuator table:
    python3 tools/compute_physical_params.py
"""
import csv
import os
import struct

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
CSV = os.path.join(PKG, 'cad', 'aibomech_agrobot_v2_mass_properties.csv')
OUT = os.path.join(PKG, 'config', 'arm_physical.yaml')

# Actuators, placed at the child-joint origin inside the link that carries them.
# Mass includes bracket and horn. Box size (x, y, z) is used for its inertia.
# Reference part: 12 V smart serial-bus servo (Feetech STS3215 / Dynamixel
# XL430 class), a 9 g micro servo drives the gripper rack.
ACTUATORS = {
    'base_link': dict(mass=0.060, at=(-0.0905, 0.0, 0.1735), box=(0.045, 0.025, 0.035)),
    'link_1': dict(mass=0.060, at=(-0.12, 0.0, 0.0), box=(0.045, 0.035, 0.025)),
    'link_2': dict(mass=0.060, at=(-0.12, 0.013028, 0.0), box=(0.045, 0.035, 0.025)),
    'link_3': dict(mass=0.060, at=(-0.041826, 0.0, 0.115), box=(0.045, 0.025, 0.035)),
    'link_4': dict(mass=0.020, at=(-0.075, 0.080174, 0.0), box=(0.023, 0.012, 0.023)),
    'link_5': None,
}
# link_4 x coordinates where the gripper body ends and where the straight part
# of the fixed jaw starts (the curved root in between is left uncovered).
GRIPPER_BODY_END_X = -0.082
GRIPPER_JAW_START_X = -0.100
# Cable harness, screws and printed-part infill correction.
EXTRA_MASS_FACTOR = 1.10


def read_stl(path):
    data = open(path, 'rb').read()
    count = struct.unpack('<I', data[80:84])[0]
    rec = np.dtype([('n', '<3f4'), ('v', '<9f4'), ('a', '<u2')])
    tris = np.frombuffer(data[84:84 + count * 50], dtype=rec)
    return tris['v'].reshape(-1, 3).astype(float)


def box_inertia(m, size):
    x, y, z = size
    return np.diag([m * (y * y + z * z), m * (x * x + z * z), m * (x * x + y * y)]) / 12.0


def combine(bodies):
    mass = sum(m for m, _, _ in bodies)
    com = sum(m * c for m, c, _ in bodies) / mass
    inertia = np.zeros((3, 3))
    for m, c, i in bodies:
        d = c - com
        inertia += i + m * (d @ d * np.eye(3) - np.outer(d, d))
    return mass, com, inertia


def check_inertia(name, inertia):
    ev = np.linalg.eigvalsh(inertia)
    a, b, c = sorted(ev)
    assert a > 0 and a + b >= c * (1 - 1e-9), f'{name}: non-physical inertia {ev}'


def main():
    rows = {r['Link Name']: r for r in csv.DictReader(open(CSV))}
    lines = ['# Generated by tools/compute_physical_params.py - do not edit by hand.',
             '# Masses in kg, lengths in m, inertia in kg*m^2 about the COM in link axes.']
    for link, act in ACTUATORS.items():
        r = rows[link]
        f = lambda k: float(r[k])
        m_cad = f('Mass') * EXTRA_MASS_FACTOR
        c_cad = np.array([f('Center of Mass X'), f('Center of Mass Y'), f('Center of Mass Z')])
        i_cad = np.array([
            [f('Moment Ixx'), f('Moment Ixy'), f('Moment Ixz')],
            [f('Moment Ixy'), f('Moment Iyy'), f('Moment Iyz')],
            [f('Moment Ixz'), f('Moment Iyz'), f('Moment Izz')]]) * EXTRA_MASS_FACTOR
        bodies = [(m_cad, c_cad, i_cad)]
        if act:
            bodies.append((act['mass'], np.array(act['at']), box_inertia(act['mass'], act['box'])))
        mass, com, inertia = combine(bodies)
        check_inertia(link, inertia)

        verts = read_stl(os.path.join(PKG, 'meshes', f'{link}.STL'))
        boxes = {'collision_box': verts}
        if link == 'base_link':
            # L-shaped column: foot plate, post, top bracket carrying J1.
            # The post has no vertices along its length, so it is spanned from
            # the top of the foot to the underside of the bracket.
            top = verts[(verts[:, 0] >= -0.016) & (verts[:, 2] >= 0.169)]
            post = np.vstack([top, top * [1, 1, 0] + [0, 0, 0.010]])
            boxes = {'collision_box': verts[verts[:, 2] <= 0.011],
                     'collision_box_post': post,
                     'collision_box_bracket': verts[verts[:, 2] >= 0.169]}
        if link == 'link_4':
            # One box would fill the space between the jaws, so the gripper
            # body and the fixed jaw get separate boxes.
            boxes = {'collision_box': verts[verts[:, 0] > GRIPPER_BODY_END_X],
                     'collision_box_jaw': verts[verts[:, 0] <= GRIPPER_JAW_START_X]}

        lines += [
            f'{link}:',
            f'  mass: {mass:.6f}',
            f'  com: {{x: {com[0]:.6f}, y: {com[1]:.6f}, z: {com[2]:.6f}}}',
            f'  inertia: {{ixx: {inertia[0,0]:.4e}, ixy: {inertia[0,1]:.4e}, ixz: {inertia[0,2]:.4e}, '
            f'iyy: {inertia[1,1]:.4e}, iyz: {inertia[1,2]:.4e}, izz: {inertia[2,2]:.4e}}}',
        ]
        for key, pts in boxes.items():
            lo, hi = pts.min(0), pts.max(0)
            centre, size = (lo + hi) / 2, np.maximum(hi - lo, 0.004)
            lines.append(
                f'  {key}: {{x: {centre[0]:.4f}, y: {centre[1]:.4f}, z: {centre[2]:.4f}, '
                f'sx: {size[0]:.4f}, sy: {size[1]:.4f}, sz: {size[2]:.4f}}}')
    with open(OUT, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
