#!/usr/bin/env python3
"""Generate the agricultural scenario worlds for Gazebo Sim (Fortress).

For every world this writes
  worlds/<name>.sdf             the world
  config/<name>_objects.yaml    ground truth of all task objects (used for
                                evaluation and the ground-truth perception mode)
  config/<name>_bridge.yaml     ros_gz_bridge topics (camera, clock, grasp joints)

Grasping in simulation: each graspable object carries a DetachableJoint
towards the gripper link (link_4). Gazebo creates such joints attached, so
sim_manager.py detaches them all while the simulation is still paused.
Fruit and weeds are additionally held by the plant / soil through a second
DetachableJoint, released when the robot cuts or pulls them.

The layout depends on the robot geometry: the arm mounting plate is at
MOUNT_HEIGHT above the floor, the rail runs along x at y = 0 and the crop
row is on the +y side.

    python3 tools/generate_worlds.py
"""
import math
import os
import random

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
MOUNT_HEIGHT = 0.85
ROBOT = 'agrobot'
GRIPPER_LINK = 'link_4'

# Colours (r g b)
RED_RIPE = (0.78, 0.04, 0.05)
UNRIPE = (0.72, 0.82, 0.45)
LEAF = (0.14, 0.45, 0.10)
LEAF_DARK = (0.08, 0.32, 0.07)
CALYX = (0.10, 0.50, 0.12)
WEED = (0.52, 0.10, 0.46)
LETTUCE = (0.45, 0.78, 0.25)
SOIL = (0.30, 0.20, 0.12)
SUBSTRATE = (0.38, 0.26, 0.15)
GUTTER = (0.92, 0.92, 0.92)
STEEL = (0.55, 0.57, 0.60)
TRAY = (0.10, 0.10, 0.11)
POT = (0.75, 0.35, 0.15)
BENCH = (0.62, 0.63, 0.60)


def material(rgb, emissive=0.0):
    r, g, b = rgb
    e = f'<emissive>{r*emissive:.3f} {g*emissive:.3f} {b*emissive:.3f} 1</emissive>' if emissive else ''
    return (f'<material><ambient>{r:.3f} {g:.3f} {b:.3f} 1</ambient>'
            f'<diffuse>{r:.3f} {g:.3f} {b:.3f} 1</diffuse>'
            f'<specular>0.1 0.1 0.1 1</specular>{e}</material>')


def pose(x=0, y=0, z=0, roll=0, pitch=0, yaw=0):
    return f'<pose>{x:.4f} {y:.4f} {z:.4f} {roll:.4f} {pitch:.4f} {yaw:.4f}</pose>'


def box(size):
    return f'<box><size>{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}</size></box>'


def cylinder(radius, length):
    return f'<cylinder><radius>{radius:.4f}</radius><length>{length:.4f}</length></cylinder>'


def sphere(radius):
    return f'<sphere><radius>{radius:.4f}</radius></sphere>'


def ellipsoid(rx, ry, rz):
    return f'<ellipsoid><radii>{rx:.4f} {ry:.4f} {rz:.4f}</radii></ellipsoid>'


def visual(name, geometry, rgb, p='', emissive=0.0):
    return f'<visual name="{name}">{p}<geometry>{geometry}</geometry>{material(rgb, emissive)}</visual>'


def collision(name, geometry, p='', mu=1.0):
    return (f'<collision name="{name}_collision">{p}<geometry>{geometry}</geometry>'
            f'<surface><friction><ode><mu>{mu}</mu><mu2>{mu}</mu2></ode></friction></surface></collision>')


def inertial(mass, size):
    x, y, z = size
    return (f'<inertial><mass>{mass}</mass><inertia>'
            f'<ixx>{mass*(y*y+z*z)/12:.3e}</ixx><iyy>{mass*(x*x+z*z)/12:.3e}</iyy>'
            f'<izz>{mass*(x*x+y*y)/12:.3e}</izz><ixy>0</ixy><ixz>0</ixz><iyz>0</iyz>'
            f'</inertia></inertial>')


def static_model(name, p, body):
    return f'<model name="{name}"><static>true</static>{p}<link name="link">{body}</link></model>'


def grasp_plugin(obj):
    """DetachableJoint object <-> gripper, driven by the task over ROS topics."""
    return (f'<plugin filename="ignition-gazebo-detachable-joint-system" '
            f'name="ignition::gazebo::systems::DetachableJoint">'
            f'<parent_link>link</parent_link><child_model>{ROBOT}</child_model>'
            f'<child_link>{GRIPPER_LINK}</child_link>'
            f'<attach_topic>/agrobot/sim/{obj}/attach_gripper</attach_topic>'
            f'<detach_topic>/agrobot/sim/{obj}/detach_gripper</detach_topic>'
            f'<suppress_child_warning>true</suppress_child_warning></plugin>')


def anchor_plugin(parent_link, obj):
    """DetachableJoint holding an object on its plant / in the soil."""
    return (f'<plugin filename="ignition-gazebo-detachable-joint-system" '
            f'name="ignition::gazebo::systems::DetachableJoint">'
            f'<parent_link>{parent_link}</parent_link><child_model>{obj}</child_model>'
            f'<child_link>link</child_link>'
            f'<detach_topic>/agrobot/sim/{obj}/detach_anchor</detach_topic></plugin>')


def world_header(name):
    return f'''<?xml version="1.0"?>
<!-- Generated by tools/generate_worlds.py - edit the generator, not this file. -->
<sdf version="1.8">
<world name="{name}">
  <physics name="1ms" type="ignored">
    <max_step_size>0.001</max_step_size>
    <real_time_factor>1.0</real_time_factor>
  </physics>
  <plugin filename="ignition-gazebo-physics-system" name="ignition::gazebo::systems::Physics"/>
  <plugin filename="ignition-gazebo-user-commands-system" name="ignition::gazebo::systems::UserCommands"/>
  <plugin filename="ignition-gazebo-scene-broadcaster-system" name="ignition::gazebo::systems::SceneBroadcaster"/>
  <plugin filename="ignition-gazebo-sensors-system" name="ignition::gazebo::systems::Sensors">
    <render_engine>ogre2</render_engine>
  </plugin>
  <gravity>0 0 -9.81</gravity>
  <scene>
    <ambient>0.55 0.55 0.55 1</ambient>
    <background>0.72 0.82 0.92 1</background>
    <shadows>true</shadows>
  </scene>
  <light type="directional" name="sun">
    <cast_shadows>true</cast_shadows>
    <pose>0 0 10 0 0 0</pose>
    <diffuse>0.85 0.85 0.82 1</diffuse>
    <specular>0.2 0.2 0.2 1</specular>
    <direction>-0.3 0.4 -0.9</direction>
  </light>
  <light type="directional" name="greenhouse_diffuse">
    <cast_shadows>false</cast_shadows>
    <pose>0 0 10 0 0 0</pose>
    <diffuse>0.35 0.35 0.35 1</diffuse>
    <specular>0 0 0 1</specular>
    <direction>0.2 -0.5 -0.8</direction>
  </light>
  <model name="floor">
    <static>true</static>
    <link name="link">
      {collision("c", '<plane><normal>0 0 1</normal><size>20 20</size></plane>')}
      {visual("v", '<plane><normal>0 0 1</normal><size>20 20</size></plane>', (0.52, 0.52, 0.50))}
    </link>
  </model>
'''


def greenhouse_frame(x_min, x_max):
    """Posts and roof beams, purely visual context."""
    parts = []
    for i, x in enumerate([x_min + k * 1.6 for k in range(int((x_max - x_min) / 1.6) + 1)]):
        for side, y in (('a', -0.9), ('b', 1.4)):
            parts.append(static_model(
                f'post_{i}{side}', pose(x, y, 1.5),
                visual('v', box((0.06, 0.06, 3.0)), STEEL)))
    return '\n'.join(parts)


class World:
    def __init__(self, name, description):
        self.name = name
        self.description = description
        self.sdf = [world_header(name)]
        self.objects = []    # ground truth
        self.grasp = []      # objects with a gripper joint
        self.anchored = []   # objects with an anchor joint

    def add(self, text):
        self.sdf.append(text)

    def write(self):
        self.sdf.append('</world>\n</sdf>\n')
        with open(os.path.join(PKG, 'worlds', f'{self.name}.sdf'), 'w') as fh:
            fh.write('\n'.join(self.sdf))
        with open(os.path.join(PKG, 'config', f'{self.name}_objects.yaml'), 'w') as fh:
            fh.write(f'# Generated by tools/generate_worlds.py\n# {self.description}\n')
            fh.write(f'world: {self.name}\nmount_height: {MOUNT_HEIGHT}\nobjects:\n')
            for o in self.objects:
                fh.write(f"  - {{name: {o['name']}, type: {o['type']}, "
                         f"x: {o['x']:.4f}, y: {o['y']:.4f}, z: {o['z']:.4f}"
                         + ''.join(f', {k}: {v}' for k, v in o.items()
                                   if k not in ('name', 'type', 'x', 'y', 'z')) + '}\n')
        with open(os.path.join(PKG, 'config', f'{self.name}_bridge.yaml'), 'w') as fh:
            fh.write('# Generated by tools/generate_worlds.py\n')
            fh.write(bridge_entries(self.name, self.grasp, self.anchored))
        print(f'{self.name}: {len(self.objects)} objects')


def bridge_entry(ros, gz, ros_type, gz_type, direction):
    return (f'- ros_topic_name: "{ros}"\n  gz_topic_name: "{gz}"\n'
            f'  ros_type_name: "{ros_type}"\n  gz_type_name: "{gz_type}"\n  direction: {direction}\n')


def bridge_entries(world, grasp, anchored):
    out = [
        bridge_entry('/clock', '/clock', 'rosgraph_msgs/msg/Clock', 'ignition.msgs.Clock', 'GZ_TO_ROS'),
        # Same topic names as the realsense2_camera driver on the real robot.
        bridge_entry('/camera/color/image_raw', '/agrobot/camera/image',
                     'sensor_msgs/msg/Image', 'ignition.msgs.Image', 'GZ_TO_ROS'),
        bridge_entry('/camera/color/camera_info', '/agrobot/camera/camera_info',
                     'sensor_msgs/msg/CameraInfo', 'ignition.msgs.CameraInfo', 'GZ_TO_ROS'),
        bridge_entry('/camera/aligned_depth_to_color/image_raw', '/agrobot/camera/depth_image',
                     'sensor_msgs/msg/Image', 'ignition.msgs.Image', 'GZ_TO_ROS'),
        bridge_entry('/camera/depth/color/points', '/agrobot/camera/points',
                     'sensor_msgs/msg/PointCloud2', 'ignition.msgs.PointCloudPacked', 'GZ_TO_ROS'),
        bridge_entry('/agrobot/sim/model_poses', f'/world/{world}/dynamic_pose/info',
                     'tf2_msgs/msg/TFMessage', 'ignition.msgs.Pose_V', 'GZ_TO_ROS'),
    ]
    for obj in grasp:
        for action in ('attach_gripper', 'detach_gripper'):
            topic = f'/agrobot/sim/{obj}/{action}'
            out.append(bridge_entry(topic, topic, 'std_msgs/msg/Empty', 'ignition.msgs.Empty', 'ROS_TO_GZ'))
    for obj in anchored:
        topic = f'/agrobot/sim/{obj}/detach_anchor'
        out.append(bridge_entry(topic, topic, 'std_msgs/msg/Empty', 'ignition.msgs.Empty', 'ROS_TO_GZ'))
    return ''.join(out)


# --------------------------------------------------------------------------
# Scenario 1: table-top strawberries in a greenhouse (harvesting, inspection)
# --------------------------------------------------------------------------
def strawberry_greenhouse(rng):
    w = World('strawberry_greenhouse',
              'Elevated strawberry gutter along the rail, ripe and unripe fruit hanging over the aisle edge.')
    m = MOUNT_HEIGHT
    gutter_front, gutter_back = 0.215, 0.415
    gutter_bottom, gutter_top = m + 0.07, m + 0.15
    x0, x1 = -0.3, 3.3
    w.add(greenhouse_frame(-0.4, 3.4))
    gy = (gutter_front + gutter_back) / 2
    gz = (gutter_bottom + gutter_top) / 2
    body = (visual('gutter', box((x1 - x0, gutter_back - gutter_front, gutter_top - gutter_bottom)), GUTTER)
            + collision('gutter', box((x1 - x0, gutter_back - gutter_front, gutter_top - gutter_bottom)))
            + visual('substrate', box((x1 - x0, 0.16, 0.01)), SUBSTRATE,
                     pose(0, 0, (gutter_top - gutter_bottom) / 2 + 0.005)))
    for k, x in enumerate([x0 + 0.2 + i * 0.8 for i in range(5)]):
        h = gutter_bottom
        body += visual(f'leg_{k}', box((0.04, 0.04, h)), STEEL, pose(x - (x0 + x1) / 2, 0, -gz + h / 2))
    w.add(static_model('gutter', pose((x0 + x1) / 2, gy, gz), body))

    fruit_id = 0
    for p, px in enumerate([0.40, 0.80, 1.20, 1.60, 2.00, 2.40]):
        crown_z = gutter_top + 0.02
        plant = f'plant_{p}'
        links = [f'<link name="crown">{inertial(0.3, (0.05, 0.05, 0.05))}'
                 + visual('crown', cylinder(0.02, 0.03), LEAF_DARK)]
        # Trifoliate leaves on petioles, spread over the gutter.
        for leaf in range(6):
            ang = rng.uniform(0, 2 * math.pi)
            r = rng.uniform(0.04, 0.09)
            lx, ly = r * math.cos(ang), abs(r * math.sin(ang)) * 0.8 + 0.02
            lz = rng.uniform(0.05, 0.12)
            links.append(visual(f'petiole_{leaf}', cylinder(0.002, lz), CALYX, pose(lx * 0.5, ly * 0.5, lz / 2)))
            for t in range(3):
                a = ang + (t - 1) * 0.7
                links.append(visual(f'leaf_{leaf}_{t}', ellipsoid(0.028, 0.018, 0.003),
                                    LEAF if t != 1 else LEAF_DARK,
                                    pose(lx + 0.02 * math.cos(a), ly + 0.02 * math.sin(a), lz, 0.2, 0.15, a)))
        plugins = []
        n_fruit = rng.choice([3, 3, 4])
        offsets = sorted(rng.sample([-0.09, -0.06, -0.03, 0.0, 0.03, 0.06, 0.09], n_fruit))
        for dx in offsets:
            ripe = rng.random() < 0.65
            name = f'fruit_{fruit_id}'
            fruit_id += 1
            fx = px + dx + rng.uniform(-0.008, 0.008)
            fy = gutter_front - 0.022 + rng.uniform(-0.004, 0.004)
            fz = m + rng.uniform(0.020, 0.045)
            # Peduncle from the gutter edge down to the calyx (stays on the plant).
            top = (fx - px, gutter_front - gy + 0.105, gutter_top - crown_z + 0.005)
            bot = (fx - px, fy - gy + 0.105, fz + 0.016 - crown_z)
            length = math.dist(top, bot)
            pitch = math.atan2(top[1] - bot[1], top[2] - bot[2])
            links.append(visual(f'peduncle_{name}', cylinder(0.0015, length), CALYX,
                                pose((top[0] + bot[0]) / 2, (top[1] + bot[1]) / 2, (top[2] + bot[2]) / 2,
                                     -pitch, 0, 0)))
            plugins.append(anchor_plugin('crown', name))
            w.add(fruit_model(name, fx, fy, fz, ripe))
            w.grasp.append(name)
            w.anchored.append(name)
            w.objects.append({'name': name, 'type': 'strawberry_ripe' if ripe else 'strawberry_unripe',
                              'x': fx, 'y': fy, 'z': fz, 'plant': plant})
        links.append('</link>')
        # Static: a joint to "world" in more than one model freezes the robot's
        # rail joint in Gazebo Fortress (gz-physics dartsim).
        w.add(f'<model name="{plant}"><static>true</static>{pose(px, gy - 0.105, crown_z)}'
              + ''.join(links) + ''.join(plugins) + '</model>')
        w.objects.append({'name': plant, 'type': 'plant', 'x': px, 'y': gy - 0.105, 'z': crown_z})
    w.write()


def fruit_model(name, x, y, z, ripe):
    colour = RED_RIPE if ripe else UNRIPE
    # Collision is a small core so the jaws never push the fruit (see module doc).
    return (f'<model name="{name}">{pose(x, y, z)}<link name="link">'
            + inertial(0.015, (0.019, 0.019, 0.024))
            + visual('berry', ellipsoid(0.0095, 0.0095, 0.012), colour, emissive=0.15 if ripe else 0.0)
            + visual('calyx', cylinder(0.009, 0.003), CALYX, pose(0, 0, 0.012))
            + collision('core', sphere(0.004))
            + '</link>' + grasp_plugin(name) + '</model>')


# --------------------------------------------------------------------------
# Scenario 2: nursery bench (seedling transplanting)
# --------------------------------------------------------------------------
TRAY_FLOOR = MOUNT_HEIGHT - 0.098


def nursery_transplanting(rng):
    w = World('nursery_transplanting',
              'Potting bench: a plug tray with seedlings and an empty pot grid along the rail.')
    bench_top = TRAY_FLOOR - 0.004
    w.add(greenhouse_frame(-0.4, 2.8))
    body = (visual('top', box((2.4, 0.30, 0.03)), BENCH) + collision('top', box((2.4, 0.30, 0.03))))
    for k, (dx, dy) in enumerate([(-1.15, -0.13), (1.15, -0.13), (-1.15, 0.13), (1.15, 0.13)]):
        body += visual(f'leg_{k}', box((0.04, 0.04, bench_top - 0.03)), STEEL,
                       pose(dx, dy, -(bench_top - 0.03) / 2 - 0.015))
    w.add(static_model('bench', pose(1.2, 0.30, bench_top - 0.015), body))

    # Plug tray: 2 x 4 cells, 50 mm pitch, 20 mm high walls.
    cols, rows, pitch = 4, 2, 0.05
    tray_x, tray_y = 0.45, 0.26
    tray = visual('base', box((cols * pitch + 0.01, rows * pitch + 0.01, 0.004)), TRAY) \
        + collision('base', box((cols * pitch + 0.01, rows * pitch + 0.01, 0.004)))
    for i in range(cols + 1):
        x = (i - cols / 2) * pitch
        tray += visual(f'wx{i}', box((0.002, rows * pitch, 0.02)), TRAY, pose(x, 0, 0.012)) \
            + collision(f'wx{i}', box((0.002, rows * pitch, 0.02)), pose(x, 0, 0.012))
    for j in range(rows + 1):
        y = (j - rows / 2) * pitch
        tray += visual(f'wy{j}', box((cols * pitch, 0.002, 0.02)), TRAY, pose(0, y, 0.012)) \
            + collision(f'wy{j}', box((cols * pitch, 0.002, 0.02)), pose(0, y, 0.012))
    w.add(static_model('plug_tray', pose(tray_x + (cols - 1) * pitch / 2, tray_y + (rows - 1) * pitch / 2,
                                         bench_top + 0.002), tray))
    sid = 0
    for i in range(cols):
        for j in range(rows):
            name = f'seedling_{sid}'
            sid += 1
            x, y = tray_x + i * pitch, tray_y + j * pitch
            z = TRAY_FLOOR + 0.0175
            w.add(seedling_model(name, x, y, z, rng))
            w.grasp.append(name)
            w.objects.append({'name': name, 'type': 'seedling', 'x': x, 'y': y, 'z': z, 'cell': f'{i}-{j}'})

    # Pots: 2 x 4 grid, 100 mm pitch, soil surface 36 mm above the bench.
    pid = 0
    for i in range(4):
        for j in range(2):
            name = f'pot_{pid}'
            pid += 1
            x, y = 1.10 + i * 0.10, 0.24 + j * 0.08
            soil = bench_top + 0.036
            pot = (visual('shell', cylinder(0.034, 0.045), POT, pose(0, 0, 0.0225))
                   + visual('soil', cylinder(0.031, 0.002), SOIL, pose(0, 0, 0.035))
                   + collision('soil', cylinder(0.031, 0.036), pose(0, 0, 0.018)))
            w.add(static_model(name, pose(x, y, bench_top), pot))
            w.objects.append({'name': name, 'type': 'pot', 'x': x, 'y': y, 'z': soil})
    w.write()


def seedling_model(name, x, y, z, rng):
    body = (inertial(0.012, (0.018, 0.018, 0.035))
            + visual('plug', box((0.018, 0.018, 0.035)), SOIL)
            + visual('stem', cylinder(0.0015, 0.03), CALYX, pose(0, 0, 0.032))
            + collision('core', box((0.010, 0.010, 0.035)), mu=1.5))
    for k in range(3):
        a = k * 2.1 + rng.uniform(-0.3, 0.3)
        body += visual(f'leaf{k}', ellipsoid(0.014, 0.007, 0.002), LEAF,
                       pose(0.012 * math.cos(a), 0.012 * math.sin(a), 0.047, 0.25, 0, a))
    return (f'<model name="{name}">{pose(x, y, z)}<link name="link">{body}</link>'
            + grasp_plugin(name) + '</model>')


# --------------------------------------------------------------------------
# Scenario 3: raised bed with lettuce and weeds (precision weeding)
# --------------------------------------------------------------------------
def weeding_bed(rng):
    w = World('weeding_bed', 'Raised lettuce bed with purple broadleaf weeds between the crop plants.')
    soil_z = MOUNT_HEIGHT - 0.09
    w.add(greenhouse_frame(-0.4, 3.0))
    bed_x0, bed_x1, bed_y0, bed_y1 = 0.10, 2.70, 0.16, 0.44
    bx, by = (bed_x0 + bed_x1) / 2, (bed_y0 + bed_y1) / 2
    bed = (f'<link name="bed">{inertial(80.0, (bed_x1 - bed_x0, bed_y1 - bed_y0, 0.3))}'
           + visual('soil', box((bed_x1 - bed_x0, bed_y1 - bed_y0, 0.02)), SOIL)
           + collision('soil', box((bed_x1 - bed_x0, bed_y1 - bed_y0, 0.02)))
           + visual('frame_front', box((bed_x1 - bed_x0, 0.02, 0.06)), (0.45, 0.33, 0.2),
                    pose(0, -(bed_y1 - bed_y0) / 2, -0.02))
           + visual('frame_back', box((bed_x1 - bed_x0, 0.02, 0.06)), (0.45, 0.33, 0.2),
                    pose(0, (bed_y1 - bed_y0) / 2, -0.02)))
    for k, (dx, dy) in enumerate([(-1.25, -0.12), (1.25, -0.12), (-1.25, 0.12), (1.25, 0.12)]):
        bed += visual(f'leg_{k}', box((0.05, 0.05, soil_z - 0.04)), STEEL, pose(dx, dy, -(soil_z - 0.04) / 2 - 0.01))

    crops = []
    for i, cx in enumerate([0.30 + k * 0.30 for k in range(8)]):
        cy = 0.35 + rng.uniform(-0.01, 0.01)
        crops.append((cx, cy))
        bed += lettuce_visual(f'lettuce_{i}', cx - bx, cy - by, 0.01, rng)
        w.objects.append({'name': f'lettuce_{i}', 'type': 'lettuce', 'x': cx, 'y': cy, 'z': soil_z + 0.01})
    bed += '</link>'

    weeds, plugins = [], []
    while len(weeds) < 8:
        x, y = rng.uniform(0.35, 2.35), rng.uniform(0.21, 0.29)
        if all(math.dist((x, y), c) > 0.10 for c in crops) and all(math.dist((x, y), q) > 0.09 for q in weeds):
            weeds.append((x, y))
    weeds.sort()
    for k, (x, y) in enumerate(weeds):
        name = f'weed_{k}'
        z = soil_z + 0.01
        w.add(weed_model(name, x, y, z, rng))
        plugins.append(anchor_plugin('bed', name))
        w.grasp.append(name)
        w.anchored.append(name)
        w.objects.append({'name': name, 'type': 'weed', 'x': x, 'y': y, 'z': z})
    w.add(f'<model name="raised_bed"><static>true</static>{pose(bx, by, soil_z)}{bed}'
          + ''.join(plugins) + '</model>')
    w.write()


def lettuce_visual(name, x, y, z, rng):
    out = visual(f'{name}_heart', ellipsoid(0.03, 0.03, 0.025), LETTUCE, pose(x, y, z + 0.025))
    for k in range(7):
        a = k * 2 * math.pi / 7 + rng.uniform(-0.2, 0.2)
        out += visual(f'{name}_leaf{k}', ellipsoid(0.04, 0.022, 0.006), LETTUCE if k % 2 else (0.35, 0.68, 0.2),
                      pose(x + 0.03 * math.cos(a), y + 0.03 * math.sin(a), z + 0.02, 0, -0.5, a))
    return out


def weed_model(name, x, y, z, rng):
    body = (inertial(0.008, (0.02, 0.02, 0.04))
            + visual('stem', cylinder(0.003, 0.035), (0.35, 0.12, 0.25), pose(0, 0, 0.0175))
            + collision('core', cylinder(0.003, 0.035), pose(0, 0, 0.0175)))
    for k in range(5):
        a = k * 2 * math.pi / 5 + rng.uniform(-0.3, 0.3)
        body += visual(f'leaf{k}', ellipsoid(0.016, 0.008, 0.002), WEED,
                       pose(0.014 * math.cos(a), 0.014 * math.sin(a), 0.006 + 0.004 * (k % 2), 0, -0.3, a))
    body += visual('top', ellipsoid(0.008, 0.008, 0.004), WEED, pose(0, 0, 0.036))
    return (f'<model name="{name}">{pose(x, y, z)}<link name="link">{body}</link>'
            + grasp_plugin(name) + '</model>')


if __name__ == '__main__':
    os.makedirs(os.path.join(PKG, 'worlds'), exist_ok=True)
    os.makedirs(os.path.join(PKG, 'config'), exist_ok=True)
    strawberry_greenhouse(random.Random(11))
    nursery_transplanting(random.Random(12))
    weeding_bed(random.Random(13))
